server:
  port: 8500

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gyndowind?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 50
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      filters: stat,wall,log4j
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      mybatis:
        configuration:
          cache-enabled: false
          local-cache-scope: session

nps:
  auth-key: sun55kong
  host: http://127.0.0.1:8080
  client-add-url: /client/add
  client-del-url: /client/del
  client-get-url: /client/list
  tunnel-get-url: /index/gettunnel
  tunnel-add-url: /index/add
  tunnel-edit-url: /index/edit
  tunnel-del-url: /index/del
